### ISSUE TITLE
Favicon manquante

### ISSUE THREAD

**Issue by bfresnel** [The-Fltaushnt-Crew/roshbet#9]
Quand nous ouvrons la console développeur, nous avons ce message d'erreur : 
![image](https://user-images.githubusercontent.com/5629642/212779970-db729c3d-92f0-44d8-b6f8-2a0c60bb26ec.png)

Il nous manque un favicon (un logo qui s'affichera dans l'onglet du navigateur). Nous pourrions rajouter le "R" en logo favicon

**Comment by bfresnel** [comment]
après quelques clics de recherche, j'ai trouvé un site qui fait directement les ico. J'ai directement tout mis dans le fichier zip : 
- [favicon_ico.zip](https://github.com/The-Fltaushnt-Crew/roshbet/files/10429964/favicon_ico.zip)

Il faut maintenant intégrer le fichier `favicon.ico` à la racine du projet. Au prochain affichage, on devrait avoir le logo qui s'affiche dans l'onglet de notre navigateur.

**Comment by Shaktas** [comment]
j'ajoute un fichier zip de favicon pour le site avec un background color Black celui qui tu as envoyé est transparent et si l'onglet est blanc on ne verra pas le R .

- [favicon-black-background.zip](https://github.com/The-Fltaushnt-Crew/roshbet/files/10432065/favicon-black-background.zip)

pour un raison que j'ignore le .ico du zip est transparent malgré le fond noir ce qui n'arrive pas avec les .png.

pour l'appliquer dans le code du site j'amerai attendre le merge "site skeleton" avant sa évitera un conflit ^^

**Comment by bfresnel** [comment]
@Shaktas la PR #8 a été mergée donc si tu as envie de t'amuser c'est maintenant
